---
# tasks file for hswong3i.php_fpm_vhosts

- name: create user
  user:
    name={{ php_fpm_vhosts_user }}
    password={{ php_fpm_vhosts_pass }}
    home={{ php_fpm_vhosts_home }}
    shell=/bin/bash
  notify: restart php_fpm
  tags: hswong3i.php_fpm_vhosts

- name: prepare file
  file:
    path={{ item.path }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
    state={{ item.state }}
  with_items:
  - { path: "{{ php_fpm_vhosts_session_save_path }}", owner: "{{ php_fpm_vhosts_user }}", group: "{{ php_fpm_vhosts_user }}", mode: '0755', state: 'directory' }
  - { path: "{{ php_fpm_vhosts_upload_tmp_dir }}", owner: "{{ php_fpm_vhosts_user }}", group: "{{ php_fpm_vhosts_user }}", mode: '0755', state: 'directory' }
  notify: restart php_fpm
  tags: hswong3i.php_fpm_vhosts

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/php/7.0/fpm/pool.d/www.conf.j2', dest: "/etc/php/7.0/fpm/pool.d/{{ php_fpm_vhosts_user }}.conf", owner: 'root', group: 'root', mode: '0644' }
  notify: restart php_fpm
  tags: hswong3i.php_fpm_vhosts
