---
# tasks file for hswong3i.php_vhosts

- name: create group
  group:
    name: "{{ php_vhosts_user }}"
    gid: "{{ php_vhosts_gid | default(None) or omit }}"
  when: php_vhosts_pass is string and php_vhosts_hash_salt is string
  notify: restart php
  tags: hswong3i.php_vhosts

- name: create user
  user:
    name: "{{ php_vhosts_user }}"
    password: "{{ php_vhosts_pass | password_hash('sha512', php_vhosts_hash_salt) }}"
    home: "{{ php_vhosts_home }}"
    group: "{{ php_vhosts_user }}"
    uid: "{{ php_vhosts_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: php_vhosts_pass is string and php_vhosts_hash_salt is string
  notify: restart php
  tags: hswong3i.php_vhosts

- name: prepare file
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ php_vhosts_base }}", owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", mode: "0755", state: "directory" }
    - { dest: "{{ php_vhosts_base }}/etc/php/5.6", owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", mode: "0755", state: "directory" }
    - { dest: "{{ php_vhosts_base }}/etc/php/7.0", owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", mode: "0755", state: "directory" }
    - { dest: "{{ php_vhosts_session_save_path }}", owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", mode: "0755", state: "directory" }
    - { dest: "{{ php_vhosts_upload_tmp_dir }}", owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", mode: "0755", state: "directory" }
  run_once: yes
  notify: restart php
  tags: hswong3i.php_vhosts

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/php/5.6/fpm/pool.d/www.conf.j2", dest: "/etc/php/5.6/fpm/pool.d/{{ php_vhosts_id }}.conf", owner: "{{ php_vhosts_user }}", group: "www-data", mode: "0664" }
    - { src: "etc/php/7.0/fpm/pool.d/www.conf.j2", dest: "/etc/php/7.0/fpm/pool.d/{{ php_vhosts_id }}.conf", owner: "{{ php_vhosts_user }}", group: "www-data", mode: "0664" }
  notify: restart php
  tags: hswong3i.php_vhosts

- name: symlink file
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_items:
    - { src: "/etc/php/5.6/fpm/pool.d/{{ php_vhosts_id }}.conf", dest: "{{ php_vhosts_base }}/etc/php/5.6/php.ini",  owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", state: "link" }
    - { src: "/etc/php/7.0/fpm/pool.d/{{ php_vhosts_id }}.conf", dest: "{{ php_vhosts_base }}/etc/php/7.0/php.ini",  owner: "{{ php_vhosts_user }}", group: "{{ php_vhosts_user }}", state: "link" }
  run_once: yes
  notify: restart php
  tags: hswong3i.php_vhosts
