---
# tasks file for hswong3i.php_vhosts

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.php_vhosts

- name: create group
  group:
    name: "{{ php_vhosts_user }}"
    gid: "{{ php_vhosts_gid | default(None) or omit }}"
  when: php_vhosts_pass is string and php_vhosts_hash_salt is string
  notify: restart php
  tags: hswong3i.php_vhosts

- name: create user
  user:
    name: "{{ php_vhosts_user }}"
    password: "{{ php_vhosts_pass | password_hash('sha512', php_vhosts_hash_salt) }}"
    home: "{{ php_vhosts_home }}"
    group: "{{ php_vhosts_user }}"
    uid: "{{ php_vhosts_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: php_vhosts_pass is string and php_vhosts_hash_salt is string
  notify: restart php
  tags: hswong3i.php_vhosts

- name: prepare file
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items: "{{ _php_vhosts_directory }}"
  notify: restart php
  tags: hswong3i.php_vhosts

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ _php_vhosts_template }}"
  notify: restart php
  tags: hswong3i.php_vhosts

- name: symlink file
  file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "{{ item.state }}"
  with_items: "{{ _php_vhosts_link }}"
  notify: restart php
  tags: hswong3i.php_vhosts
