---
# handlers file for hswong3i.php_vhosts

- name: restart php
  service: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "php5.6-fpm", state: "restarted" }
    - { name: "php7.1-fpm", state: "restarted" }
